# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitPatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitPatch
  pod 'Alamofire'
  pod 'SDWebImage'

  target 'GitPatchTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire'
  end

  target 'GitPatchUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire'
  end

end
